In [0]:
import numpy as np

In [100]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [101]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
print('Even COls Fetching',arr1[:,1:5:2])          #Even Columns

print('Odd COls Fetching',arr1[:,0:5:2] )    #Odd Columns



Even COls Fetching [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]
 [26 28]
 [31 33]
 [36 38]]
Odd COls Fetching [[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]]


In [102]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
arrS = arr1[:,0:5:2][0:8:3,:]
arrS


array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [103]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[8238, 2413, 1521, 7919, 8041],
       [6442, 5714, 2760, 7274, 1460]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [104]:
# Q3. Write a code to normalize arr2.

arr2=np.array([(arr2-arr2.min())/(arr2.max()-arr2.min())])
arr2

array([[[1.        , 0.14060195, 0.0089997 , 0.95293597, 0.97093538],
        [0.73502508, 0.62761877, 0.19179699, 0.85777515, 0.        ]]])

In [105]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [106]:
# Q4. How would you check if your numpy array has some missing values?
''' Missing Data are May be
      1. Unknown Yet Existing Data (np.nan)
      2. None
    These Missing Data Is being Implemented with
      1. Bit Pattern 
      2. Mask
    
    TO check Missing Data in NUmpy Array WE Can Use  
         -> numpy.isnan  for nan Type values
'''
 # M_Occur check if any missing value ocur in numpy array
def M_Occur(arr):
  if any(np.equal(arr,None)):
    return True
  return any(np.isnan(arr))


arr8=np.array([1,2,3,np.nan,4])
arr9=np.array([1,2,3,None])
arr10=np.array([1,2,3])
print('arr8',arr8,M_Occur(arr8),'\narr9',arr9,M_Occur(arr9),'\narr10',arr10,M_Occur(arr10))

# Hint: Thoda research karo numpy me existing functions hai

arr8 [ 1.  2.  3. nan  4.] True 
arr9 [1 2 3 None] True 
arr10 [1 2 3] False


In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

def large(arr,n):
  if n==1:
    return arr.max()
  lis=[i for i in arr if i%n==0]
  return max(lis)

In [0]:
arr=np.array([12,34,40,7,1,0])
n=int(input())
print(large(arr,n))

3
12
